source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'SquashPro' do
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'RKCardView'
pod 'MDCSwipeToChoose'
pod 'MBProgressHUD'
pod 'FontAwesome.swift'
pod 'paper-onboarding'
pod 'TisprCardStack'
pod 'RKCardView'
# pod "UPCarouselFlowLayout"
pod 'PinLayout'
pod 'KSTokenView', '~> 4.0'
pod 'Eureka'
pod 'Pulley'
pod "Cupcake"
pod 'Hue'
pod 'TisprCardStack'
pod 'UIColor+FlatColors'
pod 'Cartography'
pod 'EasyPeasy'
use_frameworks!
pod 'performSelector-swift'
end
